C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Alabama
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Arkansas
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Arizona
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R California
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Colorado
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Connecticut
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Delaware
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R District_of_Columbia
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Florida
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Georgia
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Idaho
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Iowa
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Illinois
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Indiana
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Kansas
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Kentucky
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Louisiana
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Massachusetts
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Maryland
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Maine
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Michigan
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Minnesota
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Missouri
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Mississippi
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Montana
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R North_Carolina
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R North_Dakota
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Nebraska
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R New_Hampshire
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R New_Jersey
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R New_Mexico
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Nevada
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R New_York
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Ohio
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Oklahoma
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Oregon
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Pennsylvania
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Rhode_Island
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R South_Carolina
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R South_Dakota
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Tennessee
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Texas
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Utah
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Virginia
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Vermont
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Washington
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Wisconsin
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R West_Virginia
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\1_Con_byState.R Wyoming
