C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Alabama
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Arkansas
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Arizona
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R California
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Colorado
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Connecticut
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Delaware
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R District_of_Columbia
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Florida
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Georgia
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Idaho
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Iowa
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Illinois
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Indiana
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Kansas
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Kentucky
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Louisiana
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Massachusetts
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Maryland
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Maine
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Michigan
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Minnesota
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Missouri
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Mississippi
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Montana
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R North_Carolina
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R North_Dakota
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Nebraska
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R New_Hampshire
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R New_Jersey
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R New_Mexico
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Nevada
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R New_York
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Ohio
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Oklahoma
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Oregon
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Pennsylvania
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Rhode_Island
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R South_Carolina
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R South_Dakota
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Tennessee
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Texas
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Utah
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Virginia
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Vermont
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Washington
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Wisconsin
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R West_Virginia
C:\\Users\abock\Documents\R\R-3.5.0\bin\x64\Rscript.exe D:\\abock\NAWQA\WQR\nawqa_wqp\4_gap_analysis\src\Filter_byState_monthly.R Wyoming
